### ISSUE TITLE
fix(sass): reject when fails

### ISSUE THREAD

**Issue by Kocal** [Yproximite/yProx-CLI#410]
https://github.com/Yproximite/yProx-CLI/blob/master/lib/plugins/build/handlers/sass.ts#L44

it should call `reject`, otherwise yprox-cli won't stop when there is a Sass error:

![Sélection_999(126)](https://user-images.githubusercontent.com/2103975/62630624-9bccc300-b92f-11e9-87dc-235785803c90.png)

**Comment by tristanbes** [comment]
suite à la remonté de @ClareO
